### ISSUE TITLE
Use existing relationship category names – Position, Education, etc

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-browser-addon#10]
Definitely up for debate, but I think relationship category names should be the same as on LittleSis – the alternative names/descriptions are a little confusing, eg "attends" = education? "is employed at" can also mean "on the board of"?

The existing relationship category names are also confusing, but people who use the extension will be familiar with them...

**Comment by aepyornis** [comment]
Another minor note here: We can completely remove lobbying relationships...our lobbying relationship data needs an overhaul and, until then, let's not let users add lobbying relationships.
