### ISSUE TITLE
New entity form link should be available even when there are search results

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-browser-addon#3]
If user enters search string that returns entity results, but none of them is a match, they should be able to navigate to new entity form.

**Comment by lizstarin** [comment]
I'm actually not sure what the workflow should be here; let's discuss. To my mind, the main thing we want to avoid is having a user enter an already-existing entity into the database. So I've erred on the side of not making "add a new entity" a default or too-easy behavior.

Some points:
-It's highly likely that a misspelled or incompletely entered name will not produce the match the user wants, even if that entity is in the database. I don't believe the search library does much or any spellcheck. I think it's preferable to guide the user towards further typing or spellchecking.
-The dropdown is currently set to display TOP results, not ALL results. Not sure how frequently this would occur, but it's possible that a fully entered and correctly spelled search string would not show the desired entity in the top results. 
-We could try some kind of entity search before the user is able to submit ("it looks like this entity already exists! are you sure you want to add?"), and we should maybe add that anyway, but to some extent that's what the dropdown is already doing. 
-Is the "add new entity" button not enough to satisfy this need?
