### ISSUE TITLE
"Add new entity" button is grayed out even when form is valid

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-browser-addon#4]
![screen shot 2017-06-12 at 1 43 03 pm](https://user-images.githubusercontent.com/4164681/27048253-16e42ede-4f79-11e7-8a4b-c5bd5770f398.png)

**Comment by lizstarin** [comment]
If I understand the sequence of events correctly, this is the expected behavior: you can't add an entity without its description (should that be optional)?

**Comment by lizstarin** [comment]
Note: "a short sentence or phrase" is stand-in text, but it's not actually a string that would be inputted.

**Comment by kconn** [comment]
Description should be optional

**Comment by lizstarin** [comment]
Got it!
