### ISSUE TITLE
Is current should allow for three options

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-browser-addon#6]
0 – not current
1 – current
null – unknown

The last category is important because whether a relationship is current is often not known.

**Comment by aepyornis** [comment]
this rails code might be relevant: https://github.com/public-accountability/littlesis-rails/blob/master/app/controllers/application_controller.rb#L129-L158

**Comment by aepyornis** [comment]
see: https://github.com/public-accountability/littlesis-rails/pull/156
