### ISSUE TITLE
When clicking extension, sometimes only bottom part of form shows up

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-browser-addon#9]
Typically when it's already been used on the page.
![screen shot 2017-06-12 at 1 40 59 pm](https://user-images.githubusercontent.com/4164681/27048474-00c81394-4f7a-11e7-8362-8817e03187a1.png)

**Comment by lizstarin** [comment]
Interesting! This has never happened to me. Can you help me try to reproduce this? Or let me know if there are any error messages in the console.

**Comment by kconn** [comment]
It typically happens after I add a relationship, navigate to another page, then come back to the page where I added the relationship and click the extension again to open it up.

**Comment by kconn** [comment]
(nothing on console)
